import type {
  AdminOverview,
  AidRequest,
  Donation,
  Donor,
  ImpactMetrics,
  MatchCandidate,
  NGO,
  Notification,
} from "@/app/_lib/types";

const now = new Date();

function isoFromNow(hours: number): string {
  return new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
}

function location(area: string, address: string, lat: number, lng: number) {
  return { area, address, city: "Hyderabad", lat, lng };
}

export const demoDonors: Donor[] = [
  {
    id: "donor-ameerpet-kitchen",
    name: "Ameerpet Community Kitchens",
    phone: "+91-90000-11001",
    donor_type: "community_kitchen",
    reliability: 88,
    preferred_radius_km: 10,
    location: location("Ameerpet", "Metro Pillar 1091, Ameerpet", 17.4375, 78.4483),
  },
  {
    id: "donor-banjara-banquet",
    name: "Banjara Banquets",
    phone: "+91-90000-11002",
    donor_type: "banquet_hall",
    reliability: 94,
    preferred_radius_km: 18,
    location: location("Banjara Hills", "Road No. 12, Banjara Hills", 17.4126, 78.438),
  },
  {
    id: "donor-hitec-cafeteria",
    name: "HITEC Cafeteria Network",
    phone: "+91-90000-11003",
    donor_type: "corporate_cafeteria",
    reliability: 82,
    preferred_radius_km: 15,
    location: location("Madhapur", "Mindspace Junction, Madhapur", 17.4504, 78.382),
  },
];

export const demoNgos: NGO[] = [
  {
    id: "ngo-seva-meals",
    name: "Seva Meals Hyderabad",
    contact_name: "Anusha Reddy",
    phone: "+91-90000-22001",
    reliability: 91,
    max_daily_capacity: 220,
    current_load: 80,
    focus_areas: ["prepared_food", "community_meals"],
    location: location("Jubilee Hills", "Road No. 36, Jubilee Hills", 17.4307, 78.4035),
  },
  {
    id: "ngo-charminar-shelter",
    name: "Charminar Shelter Collective",
    contact_name: "Syed Faisal",
    phone: "+91-90000-22002",
    reliability: 87,
    max_daily_capacity: 160,
    current_load: 50,
    focus_areas: ["prepared_food", "women_and_children"],
    location: location("Charminar", "Lad Bazaar Junction, Old City", 17.365, 78.4782),
  },
  {
    id: "ngo-kukatpally-outreach",
    name: "Kukatpally Night Outreach",
    contact_name: "Rahul Dev",
    phone: "+91-90000-22003",
    reliability: 79,
    max_daily_capacity: 140,
    current_load: 120,
    focus_areas: ["dry_rations", "night_shelter"],
    location: location("Kukatpally", "Forum Sujana Mall Road", 17.4866, 78.3899),
  },
];

export const demoRequests: AidRequest[] = [
  {
    id: "request-seva-breakfast",
    ngo_id: "ngo-seva-meals",
    title: "Breakfast service for 90 workers",
    category: "prepared_food",
    quantity_needed: 90,
    unit: "meal_boxes",
    people_served: 90,
    priority: 5,
    created_at: isoFromNow(-2),
    needed_by: isoFromNow(4),
    max_distance_km: 12,
    status: "open",
    location: location("Jubilee Hills", "Road No. 36, Jubilee Hills", 17.4307, 78.4035),
    meal_slot: "breakfast",
    notes: "Morning labour chowk distribution.",
    matched_donation_id: null,
  },
  {
    id: "request-charminar-lunch",
    ngo_id: "ngo-charminar-shelter",
    title: "Midday meals for women shelter",
    category: "prepared_food",
    quantity_needed: 60,
    unit: "meal_boxes",
    people_served: 60,
    priority: 4,
    created_at: isoFromNow(-3),
    needed_by: isoFromNow(6),
    max_distance_km: 18,
    status: "matched",
    location: location("Charminar", "Near Charminar Bus Stop", 17.365, 78.4782),
    meal_slot: "lunch",
    notes: "Needs packed vegetarian meals before 2 PM.",
    matched_donation_id: "donation-hitec-picked-up",
  },
  {
    id: "request-kukatpally-rations",
    ngo_id: "ngo-kukatpally-outreach",
    title: "Dry ration kits for night outreach",
    category: "dry_rations",
    quantity_needed: 45,
    unit: "kg",
    people_served: 120,
    priority: 3,
    created_at: isoFromNow(-5),
    needed_by: isoFromNow(18),
    max_distance_km: 22,
    status: "open",
    location: location("Kukatpally", "Forum Sujana Mall Road", 17.4866, 78.3899),
    meal_slot: null,
    notes: "Dry ration kits for three outreach points.",
    matched_donation_id: null,
  },
  {
    id: "request-charminar-dinner",
    ngo_id: "ngo-charminar-shelter",
    title: "Dinner for shelter residents",
    category: "prepared_food",
    quantity_needed: 40,
    unit: "meal_boxes",
    people_served: 40,
    priority: 3,
    created_at: isoFromNow(-1),
    needed_by: isoFromNow(8),
    max_distance_km: 20,
    status: "reserved",
    location: location("Charminar", "Shalibanda Shelter Home", 17.3554, 78.4705),
    meal_slot: "dinner",
    notes: "Reserved for evening distribution.",
    matched_donation_id: "donation-ameerpet-dinner",
  },
  {
    id: "request-seva-fulfilled",
    ngo_id: "ngo-seva-meals",
    title: "Hot meal round for metro workers",
    category: "prepared_food",
    quantity_needed: 50,
    unit: "meal_boxes",
    people_served: 50,
    priority: 4,
    created_at: isoFromNow(-26),
    needed_by: isoFromNow(-10),
    max_distance_km: 10,
    status: "fulfilled",
    location: location("Jubilee Hills", "Peddamma Temple lane", 17.425, 78.4101),
    meal_slot: null,
    notes: "Completed yesterday night.",
    matched_donation_id: "donation-banjara-delivered",
  },
];

export const demoDonations: Donation[] = [
  {
    id: "donation-banjara-lunch",
    donor_id: "donor-banjara-banquet",
    title: "Conference lunch trays",
    category: "prepared_food",
    food_type: "biryani",
    prepared_time: isoFromNow(-2.5),
    storage_condition: "insulated",
    quantity: 80,
    unit: "meal_boxes",
    meals_estimate: 80,
    safety_window_hours: 2,
    created_at: isoFromNow(-2),
    expires_at: isoFromNow(3),
    pickup_start: isoFromNow(0.5),
    pickup_end: isoFromNow(2),
    status: "available",
    location: location("Banjara Hills", "Road No. 12, Banjara Hills", 17.4126, 78.438),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "good",
    image_visual_label: "fresh",
    image_visual_confidence: 68,
    notes: "Packed veg meals from a corporate event.",
    request_id: null,
    reserved_for_request_id: null,
    picked_up_at: null,
    delivered_at: null,
  },
  {
    id: "donation-hitec-rations",
    donor_id: "donor-hitec-cafeteria",
    title: "Dry pantry surplus",
    category: "dry_rations",
    food_type: "dry_rations",
    prepared_time: isoFromNow(-8),
    storage_condition: "ambient",
    quantity: 40,
    unit: "kg",
    meals_estimate: 100,
    safety_window_hours: 12,
    created_at: isoFromNow(-6),
    expires_at: isoFromNow(48),
    pickup_start: isoFromNow(1),
    pickup_end: isoFromNow(6),
    status: "available",
    location: location("Madhapur", "Mindspace Junction, Madhapur", 17.4504, 78.382),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "good",
    image_visual_label: "fresh",
    image_visual_confidence: 64,
    notes: "Dry staples and sealed ingredients.",
    request_id: null,
    reserved_for_request_id: null,
    picked_up_at: null,
    delivered_at: null,
  },
  {
    id: "donation-ameerpet-dinner",
    donor_id: "donor-ameerpet-kitchen",
    title: "Fresh dinner parcels",
    category: "prepared_food",
    food_type: "chicken_curry",
    prepared_time: isoFromNow(-2),
    storage_condition: "insulated",
    quantity: 45,
    unit: "meal_boxes",
    meals_estimate: 45,
    safety_window_hours: 2,
    created_at: isoFromNow(-1),
    expires_at: isoFromNow(3),
    pickup_start: isoFromNow(0.25),
    pickup_end: isoFromNow(1.5),
    status: "reserved",
    location: location("Ameerpet", "Metro Pillar 1091, Ameerpet", 17.4375, 78.4483),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "good",
    image_visual_label: "fresh",
    image_visual_confidence: 71,
    notes: "Reserved for the evening shelter dinner round.",
    request_id: "request-charminar-dinner",
    reserved_for_request_id: "request-charminar-dinner",
    picked_up_at: null,
    delivered_at: null,
  },
  {
    id: "donation-hitec-picked-up",
    donor_id: "donor-hitec-cafeteria",
    title: "Early breakfast pickup",
    category: "prepared_food",
    food_type: "fried_rice",
    prepared_time: isoFromNow(-4.5),
    storage_condition: "insulated",
    quantity: 65,
    unit: "meal_boxes",
    meals_estimate: 65,
    safety_window_hours: 2,
    created_at: isoFromNow(-4),
    expires_at: isoFromNow(0.85),
    pickup_start: isoFromNow(-1),
    pickup_end: isoFromNow(0.3),
    status: "picked_up",
    location: location("Madhapur", "Knowledge City Road, Madhapur", 17.4458, 78.3772),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "medium",
    image_visual_label: "about_to_spoil",
    image_visual_confidence: 66,
    notes: "Driver has already collected the meal boxes.",
    request_id: "request-charminar-lunch",
    reserved_for_request_id: "request-charminar-lunch",
    picked_up_at: isoFromNow(-0.7),
    delivered_at: null,
  },
  {
    id: "donation-banjara-delivered",
    donor_id: "donor-banjara-banquet",
    title: "Wedding buffet surplus",
    category: "prepared_food",
    food_type: "biryani",
    prepared_time: isoFromNow(-30),
    storage_condition: "ambient",
    quantity: 50,
    unit: "meal_boxes",
    meals_estimate: 50,
    safety_window_hours: 2,
    created_at: isoFromNow(-29),
    expires_at: isoFromNow(-9),
    pickup_start: isoFromNow(-27),
    pickup_end: isoFromNow(-26),
    status: "delivered",
    location: location("Banjara Hills", "Road No. 14, Banjara Hills", 17.4151, 78.4329),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "good",
    image_visual_label: "fresh",
    image_visual_confidence: 63,
    notes: "Delivered to the metro worker night shelter.",
    request_id: "request-seva-fulfilled",
    reserved_for_request_id: "request-seva-fulfilled",
    picked_up_at: isoFromNow(-26),
    delivered_at: isoFromNow(-25),
  },
  {
    id: "donation-hitec-expired",
    donor_id: "donor-hitec-cafeteria",
    title: "Pastry counter leftovers",
    category: "bakery",
    food_type: "double_ka_meetha",
    prepared_time: isoFromNow(-8),
    storage_condition: "ambient",
    quantity: 30,
    unit: "packs",
    meals_estimate: 30,
    safety_window_hours: 1,
    created_at: isoFromNow(-7.5),
    expires_at: isoFromNow(-1),
    pickup_start: isoFromNow(-8),
    pickup_end: isoFromNow(-5),
    status: "expired",
    location: location("Madhapur", "Cyber Towers Back Gate", 17.4435, 78.3772),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "spoiled",
    image_visual_label: "spoiled",
    image_visual_confidence: 84,
    notes: "Expired before pickup confirmation.",
    request_id: null,
    reserved_for_request_id: null,
    picked_up_at: null,
    delivered_at: null,
  },
  {
    id: "donation-ameerpet-cancelled",
    donor_id: "donor-ameerpet-kitchen",
    title: "Snacks tray surplus",
    category: "prepared_food",
    food_type: "kebab",
    prepared_time: isoFromNow(-5),
    storage_condition: "ambient",
    quantity: 25,
    unit: "packs",
    meals_estimate: 25,
    safety_window_hours: 2,
    created_at: isoFromNow(-4),
    expires_at: isoFromNow(-0.65),
    pickup_start: isoFromNow(0.2),
    pickup_end: isoFromNow(1),
    status: "cancelled",
    location: location("Ameerpet", "Satyam Theatre lane", 17.4387, 78.4489),
    shelf_life_hours: null,
    image_url: null,
    image_freshness_label: "medium",
    image_visual_label: "about_to_spoil",
    image_visual_confidence: 68,
    notes: "Cancelled after venue refrigeration issue.",
    request_id: null,
    reserved_for_request_id: null,
    picked_up_at: null,
    delivered_at: null,
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    audience: "admin",
    recipient_id: null,
    title: "High-confidence match available",
    message: "Conference lunch trays can be routed to Seva Meals within a 6 km radius.",
    level: "success",
    created_at: isoFromNow(-0.3),
    read: false,
  },
  {
    id: "notif-2",
    audience: "ngo",
    recipient_id: "ngo-charminar-shelter",
    title: "Pickup in progress",
    message: "Early breakfast pickup has left donor premises and is heading to Charminar.",
    level: "info",
    created_at: isoFromNow(-0.6),
    read: false,
  },
  {
    id: "notif-3",
    audience: "donor",
    recipient_id: "donor-hitec-cafeteria",
    title: "Expiry alert",
    message: "Pastry counter leftovers expired before an NGO reservation was confirmed.",
    level: "warning",
    created_at: isoFromNow(-1),
    read: false,
  },
];

export const demoMatchesByDonationId: Record<string, MatchCandidate[]> = {
  "donation-banjara-lunch": [
    {
      request_id: "request-seva-breakfast",
      ngo_id: "ngo-seva-meals",
      request_title: "Breakfast service for 90 workers",
      ngo_name: "Seva Meals Hyderabad",
      total_score: 89.4,
      distance_km: 5.8,
      factor_scores: {
        distance: 74.4,
        expiry_urgency: 96.1,
        safety_window: 82.5,
        capacity: 100,
        demand: 92.5,
        reliability: 92.5,
      },
      explanation: "Closest high-capacity fit with an early-need request and strong reliability.",
    },
    {
      request_id: "request-charminar-lunch",
      ngo_id: "ngo-charminar-shelter",
      request_title: "Midday meals for women shelter",
      ngo_name: "Charminar Shelter Collective",
      total_score: 67.8,
      distance_km: 8.1,
      factor_scores: {
        distance: 54.9,
        expiry_urgency: 90.4,
        safety_window: 74.3,
        capacity: 100,
        demand: 79.5,
        reliability: 90.5,
      },
      explanation: "Still feasible, but the trip is longer and the request urgency is slightly lower.",
    },
  ],
  "donation-hitec-rations": [
    {
      request_id: "request-kukatpally-rations",
      ngo_id: "ngo-kukatpally-outreach",
      request_title: "Dry ration kits for night outreach",
      ngo_name: "Kukatpally Night Outreach",
      total_score: 78.5,
      distance_km: 4.6,
      factor_scores: {
        distance: 79.1,
        expiry_urgency: 71.2,
        safety_window: 96.4,
        capacity: 50,
        demand: 88.7,
        reliability: 80.5,
      },
      explanation: "Strong dry-ration fit with very low travel friction and a wide storage window.",
    },
  ],
  "donation-ameerpet-dinner": [
    {
      request_id: "request-charminar-dinner",
      ngo_id: "ngo-charminar-shelter",
      request_title: "Dinner for shelter residents",
      ngo_name: "Charminar Shelter Collective",
      total_score: 84.2,
      distance_km: 10.1,
      factor_scores: {
        distance: 49.5,
        expiry_urgency: 83.8,
        safety_window: 88.1,
        capacity: 100,
        demand: 77.8,
        reliability: 87.5,
      },
      explanation: "Reserved because the evening shelter need lines up well with the pickup window.",
    },
  ],
};

export const demoImpactMetrics: ImpactMetrics = {
  snapshot_at: now.toISOString(),
  total_donations: demoDonations.length,
  active_donations: demoDonations.filter((donation) => ["available", "requested", "reserved", "picked_up"].includes(donation.status)).length,
  delivered_donations: demoDonations.filter((donation) => donation.status === "delivered").length,
  total_quantity_kg: 50,
  meals_recovered: 50,
  co2e_avoided_kg: 125,
  open_requests: demoRequests.filter((request) => ["open", "requested", "matched", "reserved"].includes(request.status)).length,
  fulfilled_requests: demoRequests.filter((request) => request.status === "fulfilled").length,
  donors_active: 3,
  ngos_active: 3,
  delivery_success_rate: 50,
};

export const demoAdminOverview: AdminOverview = {
  snapshot_at: now.toISOString(),
  donor_count: demoDonors.length,
  ngo_count: demoNgos.length,
  donation_count: demoDonations.length,
  open_request_count: demoRequests.filter((request) => ["open", "requested", "matched", "reserved"].includes(request.status)).length,
  reserved_donation_count: demoDonations.filter((donation) => donation.status === "reserved").length,
  expiring_donations: demoDonations.filter((donation) => ["available", "reserved", "picked_up"].includes(donation.status)).slice(0, 3),
  notifications: demoNotifications,
  top_matches: [demoMatchesByDonationId["donation-banjara-lunch"][0], demoMatchesByDonationId["donation-hitec-rations"][0]],
  impact: demoImpactMetrics,
};
